### ISSUE TITLE
Dependency "abricot"

### ISSUE THREAD

**Issue by cfoellmann** [ATM-Consulting/dolibarr_module_dispatch#49]
Is there any reason why this and your other modules do not declare the dependency on `abricot`?

By setting
```php
$this->depends = array( '104999' );
```
it would be managed by the dolibarr core, right?

Or does it not depend on it to be activated? just to be present.

**Comment by atm-ph** [comment]
"Abricot" module don't need to be activated, our modules need only the present of it
