### ISSUE TITLE
Code style

### ISSUE THREAD

**Issue by cfoellmann** [ATM-Consulting/dolibarr_module_dispatch#54]
Hi @atm-consulting, @atm-ph 

what is your code style guide/rules?
I really not like the inconsistent code style. are you open to submits of code style fixes? PSR-2 style?

**Comment by atm-ph** [comment]
@FHenry

**Comment by cfoellmann** [comment]
one little additional question:
Since I use phpstorm I depend/love the power of a good IDE. But creating html by `print '';` each line makes it impossible for the IDE to detect issues like missing closing tags.

Would you be open to a general restructure?
